version: '2'
services:
  app:
    volumes:
      - ${PWD}/logs:/app/logs
    image: app
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
  mypostgres:
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=mydb